### ISSUE TITLE
VPN, Wireguard/OpenVPN

### ISSUE THREAD

**Issue by Svenum** [LinuxNews-de/host-it-yourself#6]
Evtl. möchte man seine Dienste mit einer VPN in sein Heimnetz schützen oder nur um sicher öffentliche WLAN Netze nutzen. In beiden fällen ist ein Privates VPN ins Heimnetz/die eigene Cloud eine super Lösung. Die wohl bekanntesten und verbreitesten Optionen sind OpenVPN und Wireguard.

**Comment by herry23xet** [comment]
Gerne dazu auch Lösungen, die ohne FRITZ!Box funktionieren.

**Comment by krafel** [comment]
Wie wäre es mit sowas als `docker-compose.yml`?

```
networks:
  default:
    name: macvlan-br0
    driver: macvlan
    driver_opts:
      parent:  <parent interface, e.g. eth0> 
    ipam:
      config:
        - subnet: a.b.c.0/24  # I used my home network here
          gateway: a.b.c.1     # ... and a referring gateway
          ip_range: a.b.c.128/28 # some sort of IP range to use, I used a subset of the one from my home network

services:
  adguard: #ad blocking and local DNS, set your router's DNS to this container's IP address
    container_name: adguard
    image: adguard/adguardhome
    cap_add:
      - NET_ADMIN
    ports:
      - 3000:3000/tcp
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 67:67/tcp
      - 68:68/tcp
      - 68:68/udp
      - 853:853/tcp
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: always
    networks:
      default:
        ipv4_address: <my DNS IP> #change as necessary to an UNUSED IP on your network

  wgeasy:
    image: weejewel/wg-easy
    network_mode: "bridge"
    container_name: wgeasy
    depends_on:
      - adguard
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./wireguard/conf:/etc/wireguard
    environment:
      - WG_HOST=<my VPN's hostname/IP>
      - PASSWORD=<cool password>
      - WG_DEFAULT_DNS=<my DNS IP from above>
      - WG_PERSISTENT_KEEPALIVE=25
    restart: always
    networks:
      default:
        ipv4_address: a.b.c.d #change as necessary to an UNUSED IP on your network

```

Dann noch ein paar `ip` commands in der Art:
```
ip link add macvlan-br0 link <parent interface, e.g. eth0> type macvlan  mode bridge
ip addr add <IP of the host to make it reachable from 'inside' the bridge >/32 dev macvlan-br0
ip link set macvlan-br0 up
ip route add <ip_range from above> dev macvlan-br0
```
Und fertig ist der VPN-wireguard-server mit eigenem DHCP und Webfilter über `adguard`.

Das läuft bei mir so auf meinem NAS.
